 const express= require('express')
const { createTodo } = require('./type')
const { todo } = require('./db')
 const app = express()
 const port = 3000
const cors = require('cors')
app.use(cors())
let id = 0
 let newtodo = generateRandomTodo()
let todos=[]
 app.use(express.json())
 
//  app.post('/todos',async(req,res)=>{
//           try {
//             const createPayload = req.body
//             const validatingShema= createTodo.safeParse(createPayload)
//             if(!validatingShema.success){
//                 res.status(404).json({
//                     mesg: "you send the wrong inputs"
//                 })

//             }
//             await todo.create({
//                 title : createPayload.title,
//                 description: createPayload.description,
//                 completed :false
//             })
//             res.json({
//                 mesg:"todo created"
//             })
//           } catch (error) {
//                console.log(error);
//                res.json({
//                 mesg:"something went wrong"
//                })
               
//           }
//  })

 function generateRandomTodo(){

   const randomTodo = [
    "go to gym",
    "eat food",
    "study DSA",
    "do coding",
    "go for walk",
    "read a book",
    "watch a tutorial"
   ]
   const randomIndex = Math.floor(Math.random()*randomTodo.length)
   const  randomMin = Math.floor(Math.random()*100)
//    console.log(randomMin);
   
//    console.log(randomIndex);
   
//    console.log(randomTodo[randomIndex]);
   
      return {
         id : id++,
         title: `${randomTodo[randomIndex]} for ${randomMin} min`,
         description:"this is autogenerated"
      }
 }
 app.get('/random-todo', (req,res)=>{
      newtodo = generateRandomTodo()
        //  console.log("arrray",newtodo);
         //   res.json([newtodo])
          todos.push(newtodo)
          console.log("current todo :", typeof todos);
         
          console.log(todos);
          
           res.json(todos)
 })

 app.get('/todo',(req,res)=>{
           const id     = parseInt(req.query.id)
           console.log( "all todo : ",todos);
           
           const result   = todos.find(todo=> todo.id ===id)

         //   console.log("id :",id);
         //    console.log( "match todo:",result);
           
           
        //    console.log(todo);
           
            
       
        if(result){
            res.json({result})
        }
        else{
            res.send("something went wrong")
        }
 })

 app.listen(port,(req,res)=>{
    console.log(`${port}`);
    

 })